### ISSUE TITLE
split_inputs_from_targets in module/preprocessing/common.py

### ISSUE THREAD

**Issue by VincentMagn** [ontime-re/ontime#30]
The current function is taking the beginning of the batch as the X part to train and the end as the target (Y) 
For example, with len(X) = 2 and len(Y) = 1, depending on the batch size, the "jump" between x and the prediction can change. 

With the length of the batch (in red) equals to 4, we are having a jump of 1. 

<img width="820" alt="image" src="https://github.com/fredmontet/ontime/assets/144789299/0e791ff5-3d25-4527-b83f-b85313ee3594">

With the length of the batch (in red) equals to 3, we are having a jump of 0. 

 
<img width="812" alt="image" src="https://github.com/fredmontet/ontime/assets/144789299/e163a2a5-a6de-4736-a17d-c5410782f9c8">

This behavior must should be explicitly requested from the user.

Check, if : 
- We want to avoid the problem with only adding check that len(batch) =  len(X) + len(Y) 
or / and 
- Add a new parameter (shift/jump) that is the jump between X and y then len(batch) =  len(X) + len(Y) + jump 

Make sure that the jump here is not confusing with the jump between 2 batches

**Comment by fredmontet** [comment]
Fixed in #45
