### ISSUE TITLE
split_by_length in module/preprocessing/common.py

### ISSUE THREAD

**Issue by VincentMagn** [ontime-re/ontime#31]
The argument split is not clear enough. 

It should be clear that it is the jump between the current batch and the next.
Shift = 1 

<img width="318" alt="image" src="https://github.com/fredmontet/ontime/assets/144789299/176060ea-e16d-4425-9213-cd70b917d608">

Shift = 2

<img width="319" alt="image" src="https://github.com/fredmontet/ontime/assets/144789299/86dd4dee-c9b6-4b4f-88da-0da3dcd7e79c">

**Comment by fredmontet** [comment]
Fixed in #45
